Mercari step6
cocolo93/mercari-build-training pull request #5
Opened 2024-02-23 04:03 UTC by cocolo93

2024-02-25 03:27 UTC, hinako1217 requested changes

2024-02-25 03:27 UTC, hinako1217 commented on go/app/main.go
> +	}
エラー処理で、`if err != nil`はエラーが発生したときを表すので、`return nil`じゃなくて`return err`だと思います！

2024-02-26 08:22 UTC, NamikoToriyama commented on go/db/.DS_Store
このこはmainにマージしたくないので、.gitgnoreにファイル名を追加してください。

gitの管理から外したいので、こちらの記事を参考にrmしてあげてください
https://qiita.com/megu_ma/items/a438a71c84145f14d04e

2024-02-26 11:34 UTC, NamikoToriyama approved these changes

2024-02-26 11:56 UTC, merged